name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
      - name: Debug: List files in root
        run: ls -l
      - name: Debug: List files in app-reliability-project
        run: ls -l app-reliability-project
      - name: Debug: Check docker-compose.yml exists
        run: |
          if [ ! -f app-reliability-project/docker-compose.yml ]; then
            echo "docker-compose.yml not found!"
            exit 1
          fi
      - name: Deploy with Docker Compose
        working-directory: app-reliability-project
        run: |
          docker-compose up -d --build
